### ISSUE TITLE
WatsonBridgeException: Watson Bridge: Bad Request

### ISSUE THREAD

**Issue by meindhoven** [findbrok/laravel-personality-insights#16] opened 2017-07-07 07:18 UTC
Hi,

I've installed v1.1 of laravel-personality-insights and have tried to start of with a Unit Test to start developing (using TDD methodology). I've setup all of the necessary credentials and know they are working by testing some API calls through cURL. When I run the Unit test I get the following error:

> FindBrok\WatsonBridge\Exceptions\WatsonBridgeException: Watson Bridge: Bad Request

> vendor/findbrok/php-watson-api-bridge/src/Bridge.php:225
> vendor/findbrok/php-watson-api-bridge/src/Bridge.php:490
> vendor/findbrok/php-watson-api-bridge/src/Bridge.php:507
> vendor/findbrok/php-watson-api-bridge/src/Bridge.php:446
> vendor/findbrok/laravel-personality-insights/src/AbstractPersonalityInsights.php:182
> vendor/findbrok/laravel-personality-insights/src/PersonalityInsights.php:87
> tests/InsightsTest.php:39

Using PHPUnit 5.7.21

The actual code is as follows:

    /** @test */
    function can_load_a_profile_from_array()
    {

        $singleContentItem = [
            "content" => "We dare not forget today that we are the heirs of that first revolution. Let the word go forth from this time and place, to friend and foe alike, that the torch has been passed to a new generation of Americans -- born in this century, tempered by war, disciplined by a hard and bitter peace, proud of our ancient heritage -- and unwilling to witness or permit the slow undoing of those human rights to which this nation has always been committed, and to which we are committed today at home and around the world.Let every nation know, whether it wishes us well or ill, that we shall pay any price, bear any burden, meet any hardship, support any friend, oppose any foe to assure the survival and the success of liberty. This much we pledge -- and more. To those old allies whose cultural and spiritual origins we share, we pledge the loyalty of faithful friends. United there is little we cannot do in a host of cooperative ventures. Divided there is little we can do -- for we dare not meet a powerful challenge at odds and split asunder.To those new states whom we welcome to the ranks of the free, we pledge our word that one form of colonial control shall not have passed away merely to be replaced by a far more iron tyranny. We shall not always expect to find them supporting our view. But we shall always hope to find them strongly supporting their own freedom -- and to remember that, in the past, those who foolishly sought power by riding the back of the tiger ended up inside.",
            "contenttype" => "text/plain",
            "created" => 1447639154000,
            "id" => "666073008692314113",
            "language" => "en",
            "sourceid" => "Twitter API",
            "userid" => "@Oprah"
        ];

        // Create the PI service.
        $personalityInsights = $this->app->make('PersonalityInsights');

        // Add single contentItem.
        $personalityInsights->addSingleContentItem($singleContentItem);

        $profile = $personalityInsights->getProfileFromWatson();

    }}`

Still learning on Laravel and PHP so not sure if I'm to blame for the issue.

**Comment by percymamedy** [comment] 2017-07-08 15:15
Bad Request usually means:

Login to Watson was correctly done but something in the Request must be wrong.

I think the problem is here, it seems IBM has removed the ```sourceid``` and ```userid``` from the request and is not possible to post these anymore, If am not wrong. Maybe try to remove these from your contentitem and try again.

https://www.ibm.com/watson/developercloud/personality-insights/api/v3/?curl#ContentItem

**Comment by meindhoven** [comment] 2017-07-10 08:43
I tried to strip those fields but didn't help so far. The error stays the same

> created
> userid
> sourceid

Would it be possible to get a more verbose ouput to see where the problem lies?

**Comment by percymamedy** [comment] 2017-07-10 09:10
Personality insights make use of WatsonPHPBridge package. Check in this file in the WatsonPHPBridge :

https://github.com/findbrok/php-watson-api-bridge/blob/1.1/src/Bridge.php#L218 and try to dump the response there using Laravel ```dd()``` method.

This will give you the Raw Response from WATSON itself. There must be some more info there I guess

**Comment by meindhoven** [comment] 2017-07-10 11:46
When I dd($decodedResponse) i get:
`array:3 [
  "code" => 400
  "sub_code" => "S00016"
  "error" => "No version provided"
]
`

**Comment by percymamedy** [comment] 2017-07-10 13:18
How did u add the version in ?

Try using the ```withQuery()``` method on your insights instance like so :

```php
$singleContentItem = [
     "content" => "...",
     "contenttype" => "text/plain",
     "id" => "666073008692314113",
     "language" => "en",
];

// Create the PI service.
$personalityInsights = $this->app->make('PersonalityInsights');

// Add single contentItem.
$personalityInsights->addSingleContentItem($singleContentItem);

$profile = $personalityInsights->withQuery(['version' => '2017-07-10'])->getFullProfile();
```

**Comment by meindhoven** [comment] 2017-07-10 14:36
I added the version to the array in singleContentItem. I tried your suggestion. Now it throws this error:

```
JsonMapper_Exception: Empty type at property "FindBrok\PersonalityInsights\Models\Warning::$warning_id"

/Users/martijneindhoven/Sites/SproutPsyche/vendor/netresearch/jsonmapper/src/JsonMapper.php:220
/Users/martijneindhoven/Sites/SproutPsyche/vendor/netresearch/jsonmapper/src/JsonMapper.php:376
/Users/martijneindhoven/Sites/SproutPsyche/vendor/netresearch/jsonmapper/src/JsonMapper.php:265
/Users/martijneindhoven/Sites/SproutPsyche/vendor/findbrok/laravel-personality-insights/src/PersonalityInsights.php:91
/Users/martijneindhoven/Sites/SproutPsyche/vendor/findbrok/laravel-personality-insights/src/PersonalityInsights.php:112
/Users/martijneindhoven/Sites/SproutPsyche/tests/InsightsTest.php:52
```

**Comment by meindhoven** [comment] 2017-07-10 15:09
Allright, some small steps. The single item functions throws the above error. I think because my content is too short. 

When I pass in a [JSON](https://watson-developer-cloud.github.io/doc-tutorial-downloads/personality-insights/profile.json) file (provided by IBM on their site) and pass the addContentItems->withQuery it now passes. When I parse my own JSON in exactly the same structure I get the same warning as above. 

Not sure why singleContentItem is not working but moving forward in small steps.

**Comment by percymamedy** [comment] 2017-07-10 18:21
There must be some issue then with the ```addSingleContentItem``` method.

I will look into it and try to improve it and also improve some of the features of the code like maybe automatic version passing and so and so.

Thank you for taking the time to use my Library and feedback is great so I can build something way more solid.

Am really swamped at the moment and haven't had time to even finish the Docs.

If you want to contribute in any way to this package, code or docs.. I will be very grateful and glad to accept your input.

Am closing this for now.

Thanks again.

**Closed by percymamedy** 2017-07-10 18:21 UTC
Labels: question

**Comment by meindhoven** [comment] 2017-07-11 07:20
Yes I think so too. I'll dive into it when I have the time. Thanks for your help Percy!

**Comment by percymamedy** [comment] 2017-07-15 08:05
@meindhoven :

Finally found and fixed the error with ```addSingleContentItem```. It was caused by the Warning Model, there was a missing doc block type.

https://github.com/findbrok/laravel-personality-insights/blob/b32054e75d5fa4f75374c85f2284f851452a6210/src/Models/Warning.php#L10

New release v1.1.8 should be it.

**Comment by nadnu** [comment] 2017-12-01 15:17
@percymamedy i am beginner to integration with this API...i followed your github repository installed it in local but my question i am using laravel with angular 1.6, i am unable to find the controller to call findbrok/personality-insights. i am bitter confused to use this please help me with this issue ASAP. Thank u.

**Comment by percymamedy** [comment] 2017-12-02 08:23
What do you mean "unable to find the controller to call" you should create your controller
